version: '3.8'

services:
  ambev.developerevaluation.database:  
    image: postgres:13
    container_name: ambev_developer_evaluation_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ambev.developerevaluation.rabbitmq:
    container_name: ambev_developer_evaluation_rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped 
    environment:
      RABBITMQ_DEFAULT_USER: ambev
      RABBITMQ_DEFAULT_PASS: ambev
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ambev.developerevaluation.webapi:  
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi 
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - DB_CONNECTION_STRING=Server=ambev_developer_evaluation_database;Database=developer_evaluation;User Id=developer;Password=ev@luAt10n;TrustServerCertificate=True
    depends_on:
      - ambev.developerevaluation.database
    ports:
     - "5119:80"  
     - "7181:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  postgres_data:
  rabbitmq_data:
      
networks:
  default:
    name: ambev_developer_evaluation_network
    driver: bridge
